#pragma once

#include "Pose.h"
#include "PoseProcessing.h"
#include "UnitQuaternion.h"
#include "SO3.h"
#include "AffinePose.h"
#include "AffineIncrement.h"
#include "RigidPose.h"
#include "SO3wT.h"
#include "DualQuaternion.h"
#include "PoseArrays.h"
#include "PoseCommon.h"
#include "PoseOperations.h"
#include "PoseAliases.h"